[bugfix] Exception when context is't Activity
When call ContractAction.start(), if context is not activity, the sdk think wallet is not install, then call context.startActivity(intent), throw exception.

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:1042)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1029)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
        at io.nebulas.action.ContractAction.handleException(ContractAction.java:41)
        at io.nebulas.action.ContractAction.start(ContractAction.java:31)
        at io.nebulas.api.SmartContracts.call(SmartContracts.java:119)